---
- name: Install pip modules 
  pip: 
    name: "{{ item }}" 
    state: present
  with_items:
    - awscli
    - boto
    - boto3
    - botocore

- name: install rpms
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - zlib-1.2.7
    - libffi
    - libffi-devel
    - python-devel
    - lsof
    - perl
    - tar 
    - gzip-1.5
    - curl-7.29.0
    - make
    - sudo-1.8.6p7
    - grep-2.20
    - less-458
    - ksh
    - tcsh-6.18.01
    - xalan-c-1.11.0 
    - xalan-j2-2.7.1 
    - openssh-6.6.1p1 
    - openssl-1.0.1e 
    - mailx-12.5 
    - expect-5.45 
    - tomcat 
    - puppet
    - java-1.8.0-openjdk

- name: Install puppet modules
  shell: sudo puppet module install biemond-orawls --version 1.0.60

- gem:
    name: hash-deep-merge
    state: latest  
